name: CI
on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  test:
    strategy:
      matrix:
        go-version: ["1.18", "1.19", "1.20", "1.21"]
    runs-on: ubuntu-22.04
    timeout-minutes: 5
    steps:
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
      - uses: actions/checkout@v2
      - run: go test
